const COMPLETED_STATUS = 'Completed';
const CANCELED_STATUS = 'Canceled';
const WAITING_STATUS = 'Waiting';
const DELIVERED_STATUS = 'Delivered';
const INVOICE_LOST_STATUS = 'Lost';

module.exports = {
  COMPLETED_STATUS,
  CANCELED_STATUS,
  WAITING_STATUS,
  DELIVERED_STATUS,
  INVOICE_LOST_STATUS,
};
